name: PR Validation

on:
  pull_request:
    branches:
      - master
      - staging

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate PR
        run: |
          # Get the source and target branches
          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
          TARGET_BRANCH="${{ github.event.pull_request.base.ref }}"

          # Check if the PR is from a non-master, non-staging branch to staging, or from staging to master
          if [[ "$SOURCE_BRANCH" != "master" && "$SOURCE_BRANCH" != "staging" && "$TARGET_BRANCH" == "staging" ]] || [[ "$SOURCE_BRANCH" == "staging" && "$TARGET_BRANCH" == "master" ]]; then
            echo "PR validation passed."
          else
            echo "PR Validation Failed
            Your pull request (PR) must be from your feature branch to the staging branch. After merging to staging, you should open a PR to merge staging into master.
            
            Reasons:
            Testing: Your changes need to be tested in the staging (non-prod) environment before merging to master. Use this URL for testing: Staging App.
            DB Migrations: Database migrations should first run in the staging environment (non-prod) and only afterwards in the master.
            
            Please correct the source and target branches of your pull request accordingly."
            exit 1
          fi
          